export default {
  ActionTypes: {
      NUMBER_OF_LANDS_UPDATED: "NUMBER_OF_LANDS_UPDATED",
      AVERAGES_UPDATED: "AVERAGES_UPDATED",
      MOST_COMMON_SCENARIOS_UPDATED: "MOST_COMMON_SCENARIOS_UPDATED",
      SIMULATION_DIDNT_START: "SIMULATION_DIDNT_START",
      ANALYSIS_ERROR: "ANALYSIS_ERROR",
      SELECTED_TURN_UPDATED: "SELECTED_TURN_UPDATED",
      STARTING_SIMULATION: "STARTING_SIMULATION",
      INVALID_SIMULATION: "INVALID_SIMULATION",
      QUERY_NUMBER_UPDATED: "QUERY_NUMBER_UPDATED"
  },
  Debug: true,
  Colours: ['Red', 'Blue', 'Green']
}
