export default {
  ActionTypes: {
      NUMBER_OF_LANDS_UPDATED: "NUMBER_OF_LANDS_UPDATED",
      AVERAGES_UPDATED: "AVERAGES_UPDATED",
      MOST_COMMON_SCENARIOS_UPDATED: "MOST_COMMON_SCENARIOS_UPDATED",
      SIMULATION_DIDNT_START: "SIMULATION_DIDNT_START",
      ANALYSIS_ERROR: "ANALYSIS_ERROR"
  },
  Debug: true,
  Colours: ['Red', 'Blue']
}
